version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    # Eliminado "external_links" momentáneamente para que puedas encender tu frontend con normalidad.
    network_mode: bridge
